name_tool       =  "#1932"
version    =  "1.0.0"
language   =  "EN"
creator         =  "3s_2"
Discord        =  "discord.gg/ZZT6PBM8MP"
Config      =  "https://raw.githubusercontent.com/loxy0dev/RedTiger-Tools/main/Program/Config/Config.py"
Copy_Right       =  "Copyright #1932 'GPL-3.0 license'"
