name_tool       =  "#1932"
version    =  "1.0.1"
language   =  "EN"
creator         =  "3s_2"
Discord        =  "discord.gg/ZZT6PBM8MP"
Config      =  "https://raw.githubusercontent.com/Dhebei/-1932/refs/heads/main/config.py"
Copy_Right       =  "Copyright #1932 'GPL-3.0 license'"
